# Competitor comparison pages. Facts researched October 2026. Re-check every quarter.
# Rule: only state facts we can source. Frame prices as "listed" with the check date.

CHECKED = "October 2026"

COMPARES = [
{
 "slug": "sitesthatbook-vs-jobber-website",
 "name": "Jobber",
 "short": "Jobber website",
 "title": "Jobber Website vs SitesThatBook for Contractors",
 "meta": "Jobber's built-in website builder compared with a done-for-you SitesThatBook site for home service pros: setup, cost, SEO and when to use both.",
 "h1": "Jobber website vs <em>SitesThatBook</em>",
 "lede": "Jobber includes a website builder with its field service software. Here is an honest look at when that is enough and when a done-for-you site makes more sense.",
 "answer": "If you already pay for Jobber and just need a simple online presence, its included website builder is a reasonable start at no extra cost. If you want a site that is written for your trade, built for you, and grows with monthly SEO content, SitesThatBook does that work for you. Many owners keep Jobber for scheduling and invoicing and use a separate site to win the work.",
 "rows": [
  ("What it is", "A website builder included inside Jobber's field service software", "A done-for-you website service for home service businesses"),
  ("Who builds it", "Jobber creates a starter site, then you personalize it yourself", "We write the copy, design the pages and set everything up"),
  ("Price", "Included on every Jobber plan. Jobber plans are listed from $29 a month (Core, 1 user, paid yearly)", "$349 setup, then $99 a month. No contract"),
  ("Time to launch", "Depends on how much time you spend customizing", "48 hours after your onboarding form"),
  ("Copy written for your trade and cities", "Pages are generated from the services in your Jobber account. Wording is up to you", "Written for you, service by service and city by city"),
  ("Ongoing content", "Job Showcase can publish posts about completed jobs", "2 SEO blog posts and 2 content updates every month"),
  ("Lead capture", "Request forms that flow straight into Jobber", "Click to call, text and a request form sent to you instantly"),
  ("Needs Jobber", "Yes, it is part of your Jobber account", "No. Works with any scheduling or CRM tool, including Jobber"),
 ],
 "them_fit": [
  "You already pay for Jobber and want a basic site without another bill.",
  "You want web requests to land directly in Jobber with no extra setup.",
  "You are comfortable spending time editing the site yourself.",
 ],
 "us_fit": [
  "You want the site written and built for you, without doing it yourself.",
  "You want pages written around each service and city you cover, so you show up in more local searches.",
  "You want fresh SEO content published every month without thinking about it.",
  "You want your website to stay yours even if you change scheduling software later.",
 ],
 "both": "Yes. Jobber is excellent at scheduling, quotes, invoicing and payments. Your SitesThatBook site can link to your Jobber online request form or client hub, so you keep your Jobber workflow and still get a site built to win the job.",
 "faqs": [
  ("Is the Jobber website builder free?", "Jobber says its website builder is included with every Jobber plan at no additional cost. You still need a paid Jobber plan. Check Jobber's pricing page for current plan prices."),
  ("Can I use SitesThatBook if I use Jobber?", "Yes. We build your website, and you keep using Jobber for scheduling, quotes and invoicing. We can link your site to your Jobber request form."),
  ("Which one is better for SEO?", "Both give you a site Google can read. The difference is effort: with Jobber you write and expand the content yourself, while SitesThatBook writes service and city content for you and adds 2 SEO blog posts every month."),
 ],
 "sources": [("Jobber website builder feature page", "https://www.getjobber.com/features/marketing-tools/website/"), ("Jobber pricing breakdown, September 2026", "https://www.forz.io/blog/jobber-pricing/")],
},
{
 "slug": "sitesthatbook-vs-housecall-pro-website",
 "name": "Housecall Pro",
 "short": "Housecall Pro website",
 "title": "Housecall Pro Website vs SitesThatBook",
 "meta": "Housecall Pro Websites compared with SitesThatBook for home service businesses: pricing transparency, page limits, edits, ownership and when to use both.",
 "h1": "Housecall Pro website vs <em>SitesThatBook</em>",
 "lede": "Both are done-for-you. Housecall Pro builds and manages a site as an add-on to its software. SitesThatBook is a website service on its own. Here is how they differ.",
 "answer": "Housecall Pro Websites is a good fit if you run your business on Housecall Pro and want the site tied into its booking, chat and reviews. SitesThatBook is a better fit if you want public, flat pricing, a site that does not depend on your field service software, and monthly SEO content included.",
 "rows": [
  ("What it is", "A managed website add-on for Housecall Pro customers", "A done-for-you website service for home service businesses"),
  ("Who builds it", "Housecall Pro's team builds and manages it", "Our team builds and manages it"),
  ("Price", "Websites is listed as a separate monthly add-on. The add-on price is not published. Housecall Pro plans are listed from $59 a month paid yearly", "$349 setup, then $99 a month, published on our pricing page"),
  ("Page count", "5-page and 15-page options", "5 custom pages, plus 2 new blog posts every month"),
  ("Edits", "Submitted as requests to the Housecall Pro team", "2 content updates a month included. Text or email what you want changed"),
  ("Time to launch", "Not published", "48 hours after your onboarding form"),
  ("Lead capture", "Connected to Housecall Pro online booking, chat and reviews", "Click to call, text and a request form sent to you instantly"),
  ("Needs Housecall Pro", "Yes", "No. Works alongside any software, including Housecall Pro"),
 ],
 "them_fit": [
  "You run your business on Housecall Pro and want online booking built into the site.",
  "You want one vendor for software and website.",
  "You do not mind requesting edits through their team.",
 ],
 "us_fit": [
  "You want to know the full price before you start: $349 setup, $99 a month.",
  "You want the site live in 48 hours with a live walkthrough call.",
  "You want new SEO blog posts every month without asking.",
  "You want your website separate from your software, so switching tools later does not mean losing your site.",
 ],
 "both": "Yes. Keep Housecall Pro for dispatching, invoicing and payments, and add your Housecall Pro online booking link to your SitesThatBook site so customers can still book straight into your schedule.",
 "faqs": [
  ("How much does a Housecall Pro website cost?", "Housecall Pro lists Websites as a separate monthly add-on but does not publish the add-on price on its pricing page. You need to contact Housecall Pro for a quote."),
  ("Does Housecall Pro build the website for you?", "Yes. Housecall Pro describes it as a professional website built and managed by its team, with edits handled by request."),
  ("Can I use SitesThatBook with Housecall Pro?", "Yes. We can add your Housecall Pro online booking link to your site, so jobs still land in your Housecall Pro schedule."),
 ],
 "sources": [("Housecall Pro pricing page", "https://www.housecallpro.com/pricing/"), ("Independent review of Housecall Pro websites, August 2026", "https://korekomfortsolutions.com/housecall-pro-website-builder-review/")],
},
{
 "slug": "sitesthatbook-vs-wix",
 "name": "Wix",
 "short": "Wix",
 "title": "Wix vs a Done-for-You Website for Contractors",
 "meta": "Wix compared with SitesThatBook for plumbers, HVAC, roofers and other home service pros: real cost, time, SEO setup and who should build it themselves.",
 "h1": "Wix vs a <em>done-for-you</em> website for contractors",
 "lede": "Wix is one of the most popular website builders, with a lot of flexibility. The real question for a contractor is who does the work.",
 "answer": "Wix is a strong choice if you enjoy design and have time to build and maintain the site yourself. If you would rather be on jobs than editing pages, SitesThatBook builds the site for you, writes the copy for your trade and keeps it updated for a flat monthly fee.",
 "rows": [
  ("What it is", "A do-it-yourself website builder for any type of business", "A done-for-you website service for home service businesses"),
  ("Who builds it", "You do, using templates and drag and drop tools", "We do. You fill a 10 minute form"),
  ("Price", "Paid plans listed from $17.77 to $159.77 a month, billed yearly", "$349 setup, then $99 a month. No contract"),
  ("Domain", "Free domain for the first year on paid plans", "We connect your domain. You own it"),
  ("Written for your trade", "Templates. You write the copy", "Written for your services and service area"),
  ("SEO setup", "SEO tools are built in. You set them up", "Done for you, plus 2 SEO blog posts a month"),
  ("Updates", "You make them", "2 updates a month included"),
  ("Time to launch", "Depends on your time and skill", "48 hours"),
 ],
 "them_fit": [
  "You like designing and want full control over every detail.",
  "You have evenings or weekends to build and maintain the site.",
  "You need features beyond a service business site, like a large online store.",
 ],
 "us_fit": [
  "You want a professional site without learning a website builder.",
  "You want copy written for your trade by people who write for contractors every day.",
  "You want monthly SEO blog posts and updates handled for you.",
  "You want it live in 48 hours, not someday.",
 ],
 "both": "Not usually. If you already have a Wix site, we can rebuild it on our platform and connect your existing domain, so you keep your web address.",
 "faqs": [
  ("How much does Wix cost for a small business?", "Wix lists paid plans from $17.77 to $159.77 a month when billed yearly. Prices vary by location and do not include your time to build and maintain the site."),
  ("Is Wix good for plumbers and contractors?", "It can be, if you have the time to build it well. The hard part is not the tool but the work: writing service pages, setting up SEO and keeping content fresh."),
  ("Can you move my Wix site to SitesThatBook?", "Yes. We rebuild your site, rewrite the copy for your trade and connect your existing domain."),
 ],
 "sources": [("Wix plans page", "https://www.wix.com/plans")],
},
{
 "slug": "sitesthatbook-vs-godaddy",
 "name": "GoDaddy",
 "short": "GoDaddy Website Builder",
 "title": "GoDaddy Website Builder vs SitesThatBook",
 "meta": "GoDaddy Website Builder compared with SitesThatBook for home service businesses: cost, AI setup, who does the work, SEO and monthly content.",
 "h1": "GoDaddy Website Builder vs <em>SitesThatBook</em>",
 "lede": "GoDaddy is known for domains and offers a low cost, AI assisted website builder. Here is how it compares with having the site built for you.",
 "answer": "GoDaddy's builder is one of the cheapest ways to get a basic site online, and its AI tools can get you started fast. If you want a site written for your trade, built by a team and kept fresh with monthly SEO content, SitesThatBook costs more per month but does the work for you.",
 "rows": [
  ("What it is", "A do-it-yourself website builder with AI assisted setup", "A done-for-you website service for home service businesses"),
  ("Who builds it", "You do, with AI help", "We do. You fill a 10 minute form"),
  ("Price", "A free plan with GoDaddy branding. Paid plans commonly listed around $10 to $30 a month depending on plan and billing", "$349 setup, then $99 a month. No contract"),
  ("Domain", "Free domain with annual plans", "We connect your domain. You own it"),
  ("Written for your trade", "AI generated starting copy. You edit it", "Written for your services and service area"),
  ("SEO setup", "Built-in SEO tools. You set them up", "Done for you, plus 2 SEO blog posts a month"),
  ("Updates", "You make them", "2 updates a month included"),
  ("Time to launch", "Fast to start, then depends on your time", "48 hours"),
 ],
 "them_fit": [
  "Budget is the top priority and you are fine doing it yourself.",
  "You already manage your domain and email at GoDaddy and want everything in one place.",
  "You need a simple page now and plan to upgrade later.",
 ],
 "us_fit": [
  "You want a site that sells your work, not just a page that exists.",
  "You want copy for each service and city written for you.",
  "You want monthly SEO content and updates without lifting a finger.",
  "You want a person to walk you through your site on a launch call.",
 ],
 "both": "Partly. If your domain is registered at GoDaddy, you can keep it there. We connect it to your new SitesThatBook site on launch day.",
 "faqs": [
  ("How much is GoDaddy Website Builder?", "GoDaddy offers a free plan with GoDaddy branding. Independent reviews in 2026 list paid plans roughly between $10 and $30 a month depending on the plan and whether you pay yearly. Check GoDaddy's pricing page for current prices."),
  ("Can I keep my GoDaddy domain?", "Yes. You keep your domain at GoDaddy and we point it to your new site."),
  ("Is a GoDaddy site good enough for a contractor?", "For a basic online presence, it can be. To compete in local search, you need detailed service pages, city content and regular updates, which takes time to do yourself."),
 ],
 "sources": [("GoDaddy Website Builder page", "https://www.godaddy.com/websites/website-builder"), ("Independent GoDaddy pricing review, August 2026", "https://servsw.com/godaddy-pricing")],
},
]
