# Trade page content. Each trade gets unique copy so no page is a thin duplicate.

TRADES = [
{
 "slug":"hvac-websites","name":"HVAC","who":"HVAC companies","icon":"hvac",
 "kw":"HVAC websites",
 "title":"HVAC Websites That Book Service Calls | SitesThatBook",
 "meta":"Done-for-you HVAC websites built to turn AC and furnace searches into booked calls. $349 setup, $99/month, live in 48 hours. Hosting, SEO and updates included.",
 "h1":"HVAC websites built to <em>book service calls</em>, not just look nice",
 "lede":"When the AC quits at 9pm in July, the homeowner calls the first company that looks trustworthy and answers. We build HVAC websites that win that moment. Live 48 hours after you fill the onboarding form.",
 "searches":["ac repair near me","furnace not turning on","emergency hvac service open now","heat pump installation cost","ac tune up near me"],
 "pains":[
  ("Emergency calls go to whoever shows up first","Most AC and furnace calls happen in a panic. If your phone number is buried or your site loads slowly on a phone, that homeowner backs out and taps the next listing."),
  ("Your Google Business Profile has nowhere to send people","A good map listing still needs a fast website behind it. Google uses your site to confirm what you do and where you work."),
  ("Seasonal swings hit hard","Without a site that ranks for maintenance plans and tune ups, your slow months stay slow. The right pages bring in shoulder season work."),
  ("Old sites built for desktops","Most local service searches happen on a phone. A site that pinches and zooms loses jobs every week."),
 ],
 "features":[
  ("24/7 emergency banner","A tap to call strip pinned to every page, so a homeowner with no heat reaches you in one tap."),
  ("Separate repair and install pages","AC repair, furnace repair, heat pumps, ductless minis and installs each get their own section so Google can match each search."),
  ("Maintenance plan section","Turn one-time callers into recurring customers with a clear tune up plan offer."),
  ("Financing and rebate callouts","Big ticket installs close faster when the homeowner sees financing options before they call."),
  ("Service area list","Every city and suburb you cover, written out so you show up for searches in each one."),
  ("Lead form with job type","Customers pick repair, install or maintenance so you know what the call is before you call back."),
 ],
 "pages":["Home with emergency call strip","Services: AC, heating, heat pumps, ductless, maintenance","About your company and licensing","Reviews","Contact with booking form and service area"],
 "example":("Example booking alert","No heat, gas furnace","7:42 AM . Today"),
 "faqs":[
  ("How fast can my HVAC website go live?","48 hours after you submit the onboarding form. We need your services, service area, license details, logo and a few job photos. If you do not have photos we start with clean stock imagery and swap in yours later."),
  ("Will my HVAC website show up on Google?","Every site ships with proper titles, page structure, service area content, schema markup and a sitemap submitted to Google. The Launch plan includes 2 SEO blog posts a month. For map pack visibility, the Get Found plan adds Google Business Profile management and review requests."),
  ("Can customers book a service call from the site?","Yes. Every page has click to call and a lead form that asks for the job type, address and best time. Leads go straight to your phone and email."),
  ("Do you work with commercial HVAC and refrigeration too?","Yes. We built the site for Great Northern Refrigeration in Portland, Oregon, which covers commercial, supermarket, residential and industrial HVAC and refrigeration."),
 ],
},
{
 "slug":"plumber-websites","name":"Plumbing","who":"plumbers","icon":"plumbing",
 "kw":"plumber websites",
 "title":"Plumber Websites That Get the Phone Ringing | SitesThatBook",
 "meta":"Done-for-you plumber websites built for emergency calls, drain and water heater jobs. $349 setup, $99/month, live in 48 hours with hosting and SEO included.",
 "h1":"Plumber websites that turn <em>burst pipe panic</em> into booked jobs",
 "lede":"Water on the floor means nobody is comparing ten sites. They call the first plumber who looks legit and has a big call button. We build that site for you, live 48 hours after your onboarding form.",
 "searches":["plumber near me","24 hour emergency plumber","water heater replacement","clogged drain cleaning","slab leak repair"],
 "pains":[
  ("Emergency searches need a phone number in one tap","A homeowner with a leak will not scroll. Your number has to be the first thing they see on a phone screen."),
  ("High value jobs need their own pages","Water heaters, repiping, sewer lines and slab leaks are your best tickets. One generic services page will not rank for any of them."),
  ("Trust decides the call","License number, insurance, upfront pricing and real reviews in the first screen do more selling than any slogan."),
  ("Leads lost after hours","If nobody answers at 11pm, a site with a simple request form still captures the job for the morning."),
 ],
 "features":[
  ("Emergency call strip","Sticky call and text buttons on mobile, so every visitor is one tap away from you."),
  ("Service pages for big tickets","Water heaters, drains, sewer, leak detection, repiping and fixtures each get focused copy."),
  ("License and insurance badges","Shown above the fold, where homeowners look for them."),
  ("Upfront pricing section","Optional pricing or call out fee info that filters out tire kickers."),
  ("City by city service area","Your full coverage list written out for local search."),
  ("After hours request form","Captures the job details so you can call back first thing."),
 ],
 "pages":["Home with emergency call strip","Services: drains, water heaters, leaks, sewer, repiping","About with license and insurance","Reviews","Contact with request form and service area"],
 "example":("Example booking alert","Water heater leaking","9:15 PM . Tonight"),
 "faqs":[
  ("What does a plumber website need to rank on Google?","Fast mobile pages, one clear section per main service, your service cities written out, consistent name, address and phone, schema markup and reviews. We build all of that in. Ongoing blog posts and Google Business Profile work push it further."),
  ("How much does a plumber website cost with SitesThatBook?","$349 one-time setup and $99 a month. That covers the 5-page site, hosting, SSL, 2 updates a month, 2 SEO blog posts a month and a monthly traffic report. No contracts."),
  ("Can you add my license number and insurance details?","Yes. We place license and insurance info near the top of the home page and in the footer so homeowners see it right away."),
  ("I already have a domain. Can I keep it?","Yes. You keep ownership of your domain. We connect it to the new site on launch day."),
 ],
},
{
 "slug":"roofing-websites","name":"Roofing","who":"roofers","icon":"roofing",
 "kw":"roofing websites",
 "title":"Roofing Websites That Win Estimates | SitesThatBook",
 "meta":"Done-for-you roofing websites with project galleries, financing and storm damage pages. $349 setup, $99/month, live in 48 hours. Hosting and SEO included.",
 "h1":"Roofing websites that <em>win the estimate</em> before you climb the ladder",
 "lede":"A roof is one of the biggest checks a homeowner writes. They research, compare and look for proof. We build roofing websites that show that proof clearly and turn visits into inspection requests.",
 "searches":["roofers near me","roof replacement cost","storm damage roof repair","free roof inspection","metal roofing contractor"],
 "pains":[
  ("Homeowners compare three to five roofers","Your site is the first interview. Thin pages and no project photos lose the job before you get a call."),
  ("Storm season brings out the out of town crews","A local, licensed and reviewed presence online is how you separate from storm chasers."),
  ("Financing questions slow decisions","If the homeowner cannot see financing options, the replacement gets pushed to next year."),
  ("Insurance claims confuse people","A clear claims process page builds trust and gets more storm calls."),
 ],
 "features":[
  ("Before and after gallery","Big project photos that show your workmanship on phones and desktops."),
  ("Free inspection form","Address, roof age and issue type collected up front."),
  ("Storm and insurance claim section","Explains how you help with claims, step by step."),
  ("Financing callout","Monthly payment options shown before the homeowner calls."),
  ("Manufacturer and warranty badges","Certifications and warranty terms placed where they build trust."),
  ("Service area coverage","Every town you roof in, written out for local search."),
 ],
 "pages":["Home with free inspection offer","Services: replacement, repair, storm damage, gutters","About with certifications","Reviews and project gallery","Contact with inspection form"],
 "example":("Example booking alert","Free inspection, hail damage","Sat 10:00 AM"),
 "faqs":[
  ("Can my roofing website show before and after photos?","Yes. Send your project photos with the onboarding form and we build a gallery section. We compress the images so the site stays fast."),
  ("Do roofing websites need a storm damage page?","If you do insurance work, yes. It is one of the highest intent searches in roofing after a storm, and a clear process section builds trust fast."),
  ("How long until my roofing site ranks?","Local rankings usually take a few months and depend on competition, reviews and your Google Business Profile. The site is built on a solid SEO base from day one, and the Get Found plan speeds up map pack results."),
  ("Can you show financing on my site?","Yes. Tell us your financing partner and terms in the onboarding form and we add a financing section and callouts."),
 ],
},
{
 "slug":"electrician-websites","name":"Electrical","who":"electricians","icon":"electrical",
 "kw":"electrician websites",
 "title":"Electrician Websites That Book Jobs | SitesThatBook",
 "meta":"Done-for-you electrician websites for panel upgrades, EV chargers and emergency calls. $349 setup, $99/month, live in 48 hours with hosting and SEO included.",
 "h1":"Electrician websites that <em>keep your schedule full</em>",
 "lede":"Homeowners do not hire an electrician off a hunch. They want a licensed pro who explains the work and shows up on time. We build electrician websites that prove it in the first screen.",
 "searches":["electrician near me","electrical panel upgrade cost","ev charger installation","outlet not working","whole house generator installer"],
 "pains":[
  ("Safety makes people picky","Homeowners look hard for license numbers, insurance and reviews before they let anyone touch their panel."),
  ("Growth jobs are buried","EV chargers, panel upgrades and generators are your best work. They need their own pages to rank."),
  ("Small jobs clog the phone","A short form that asks for the job type lets you sort quick fixes from big projects."),
  ("A dated site looks like a dated contractor","Fast, clean design signals you do clean, modern work."),
 ],
 "features":[
  ("License front and center","License number and insurance shown on the home page and footer."),
  ("Pages for high value work","Panel upgrades, EV chargers, generators, rewiring and lighting each get their own section."),
  ("Emergency call button","For outages and sparking outlets, one tap reaches you."),
  ("Job type request form","Sorts small repairs from big installs before you call back."),
  ("Commercial section","If you do commercial work, a separate section speaks to property managers."),
  ("Service area list","Every town you cover, written out for local search."),
 ],
 "pages":["Home with licensed and insured badges","Services: panels, EV chargers, generators, repairs","About with license details","Reviews","Contact with job request form"],
 "example":("Example booking alert","EV charger install quote","Thu 2:30 PM"),
 "faqs":[
  ("What pages should an electrician website have?","At minimum a home page, a services page with sections for each main job type, an about page with license info, reviews and a contact page. We build all 5 and add a blog with 2 SEO posts a month."),
  ("Can you target EV charger and panel upgrade searches?","Yes. Those get dedicated sections and headings so Google can match them, and they are great topics for your monthly blog posts."),
  ("Do I need to write the content?","No. You fill a short onboarding form and we write the copy. You review it on the launch call."),
  ("What if I want changes after launch?","Two updates a month are included in the $99 plan. Send a text or email with what you want changed."),
 ],
},
{
 "slug":"garage-door-websites","name":"Garage Door","who":"garage door companies","icon":"garage",
 "kw":"garage door websites",
 "title":"Garage Door Websites That Book Repairs | SitesThatBook",
 "meta":"Done-for-you garage door company websites for spring repair, openers and new doors. $349 setup, $99/month, live in 48 hours with hosting and SEO included.",
 "h1":"Garage door websites built for <em>same day repair calls</em>",
 "lede":"A broken spring traps a car and wrecks someone's morning. They search, call and book fast. We build garage door websites that put your number in front of them first.",
 "searches":["garage door repair near me","broken garage door spring","garage door opener installation","new garage door cost","garage door off track"],
 "pains":[
  ("Same day jobs go to the fastest answer","If your site does not load fast with a clear call button, the job goes to the next listing."),
  ("Lead gen sites outrank real companies","Real local companies beat national call centers with honest pages, real photos and a real address area."),
  ("New door sales need a showroom feel","Styles, materials and photos help homeowners pick and ask for a quote."),
  ("Price shoppers waste your time","A clear service call fee section filters out the people only fishing for prices."),
 ],
 "features":[
  ("Same day service banner","Call and text buttons plus a same day promise, if you offer it."),
  ("Repair vs new door paths","Repair callers and new door shoppers each get a clear path."),
  ("Door style gallery","Show the brands and styles you install."),
  ("Opener and smart controls section","Covers openers from the major brands, keypads and smart controls."),
  ("Warranty and parts info","Spring and opener warranties shown clearly."),
  ("Service area list","Every city you serve, written out for local search."),
 ],
 "pages":["Home with same day repair offer","Services: springs, openers, new doors, maintenance","About your crew","Reviews","Contact with quote form"],
 "example":("Example booking alert","Broken spring, car stuck inside","8:05 AM . Today"),
 "faqs":[
  ("Do you build websites for garage door repair companies?","Yes. Garage door is one of our core trades. We set up repair and new door paths, a gallery, a quote form and your full service area."),
  ("Can I show the door brands I install?","Yes. Tell us the brands in the onboarding form and we add them to the services and gallery sections."),
  ("Will my garage door site work on phones?","Every site is built mobile first, with a sticky call bar so callers can reach you in one tap."),
  ("Is there a contract?","No. $349 setup, then $99 a month. Cancel anytime."),
 ],
},
{
 "slug":"landscaping-websites","name":"Landscaping","who":"landscapers","icon":"landscaping",
 "kw":"landscaping websites",
 "title":"Landscaping Websites That Sell Projects | SitesThatBook",
 "meta":"Done-for-you landscaping websites with project galleries and quote forms for design, hardscape and maintenance. $349 setup, $99/month, live in 48 hours.",
 "h1":"Landscaping websites that <em>sell the yard</em> before the walkthrough",
 "lede":"Landscaping is sold with pictures. We build landscaping and lawn care websites that put your best projects up front and turn admirers into quote requests.",
 "searches":["landscaping companies near me","backyard landscape design","paver patio installation","lawn care service near me","retaining wall contractor"],
 "pains":[
  ("Your best work lives on your phone","Great project photos do nothing in your camera roll. They should be selling for you on your site."),
  ("Maintenance and design buyers want different things","Weekly lawn customers want price and reliability. Design clients want vision. One page cannot do both."),
  ("Seasonal demand","Spring rush and fall cleanups need pages ready before the season starts."),
  ("Quote requests with no detail","A form that asks for yard size and project type saves you wasted site visits."),
 ],
 "features":[
  ("Big project gallery","Before and after photos front and center."),
  ("Design build and maintenance paths","Separate sections for one-time projects and recurring service."),
  ("Hardscape section","Patios, walls, walkways and outdoor living each named for search."),
  ("Seasonal service blocks","Spring cleanups, aeration, leaf removal and snow if you offer it."),
  ("Project quote form","Collects project type, budget range and timeline."),
  ("Service area list","Every neighborhood and town you work in."),
 ],
 "pages":["Home with featured projects","Services: design, hardscape, lawn care, seasonal","About your team","Reviews and gallery","Contact with project quote form"],
 "example":("Example booking alert","Paver patio estimate","Mon 4:00 PM"),
 "faqs":[
  ("Can my landscaping website have a large photo gallery?","Yes. Send your best project photos and we build a gallery that stays fast on phones."),
  ("Do you build lawn care websites too?","Yes. Lawn care and landscape maintenance companies get the same setup with recurring service sections and a simple quote form."),
  ("Can the site promote seasonal services?","Yes. Use your 2 monthly updates to swap seasonal offers, like spring cleanups or fall leaf removal."),
  ("Have you built landscaping websites before?","Yes. We built the site for ORO Landscaping, a landscape design and build company in Colorado. You can see it on our work page."),
  ("Does the site help me rank in my town?","Every site includes your service area, local schema markup and 2 SEO blog posts a month written around local landscaping topics."),
 ],
},
{
 "slug":"cleaning-business-websites","name":"Cleaning","who":"cleaning companies","icon":"cleaning",
 "kw":"cleaning business websites",
 "title":"Cleaning Business Websites That Fill Your Calendar | SitesThatBook",
 "meta":"Done-for-you cleaning business websites for house cleaning, deep cleans and move outs, with booking forms. $349 setup, $99/month, live in 48 hours.",
 "h1":"Cleaning business websites that <em>fill your calendar</em> with recurring clients",
 "lede":"Cleaning customers decide fast and stay for years when the first visit goes well. We build cleaning websites that make booking that first visit simple.",
 "searches":["house cleaning near me","deep cleaning service","move out cleaning","recurring maid service","airbnb turnover cleaning"],
 "pains":[
  ("Clients want to know the price range","If they cannot see how pricing works, they leave to find a company that shows it."),
  ("Trust inside the home","Background checks, insurance and a satisfaction promise matter more here than in most trades."),
  ("One-time cleans that never come back","A recurring plan offer on your site turns a deep clean into a weekly client."),
  ("Back and forth over text","A booking form that asks for bedrooms, bathrooms and frequency cuts the back and forth."),
 ],
 "features":[
  ("Clear service menu","Standard, deep, move in and move out, and recurring plans, each explained."),
  ("Booking request form","Bedrooms, bathrooms, frequency and preferred day collected up front."),
  ("Trust section","Insured, background checked staff and your satisfaction promise."),
  ("Recurring plan offer","Weekly and biweekly options presented as the default choice."),
  ("Commercial cleaning section","Offices and rentals, if you serve them."),
  ("Service area list","Every neighborhood you clean in."),
 ],
 "pages":["Home with booking offer","Services: standard, deep, move out, recurring","About and trust promise","Reviews","Contact with booking form"],
 "example":("Example booking alert","Biweekly clean, 3 bed 2 bath","Fri 9:00 AM"),
 "faqs":[
  ("Can customers book a cleaning from my website?","Yes. The booking request form collects home size, service type, frequency and preferred day, then sends it to your phone and email."),
  ("Should I show prices on my cleaning website?","Showing a starting price or how pricing works usually gets more bookings. We set it up however you prefer."),
  ("Do you build websites for commercial cleaning companies?","Yes. We add a commercial section or build the whole site around offices and facilities if that is your focus."),
  ("What does the $99 a month include?","Hosting, SSL, 2 content updates a month, 2 SEO blog posts a month and a monthly traffic report."),
 ],
},
{
 "slug":"pest-control-websites","name":"Pest Control","who":"pest control companies","icon":"pest",
 "kw":"pest control websites",
 "title":"Pest Control Websites That Book Treatments | SitesThatBook",
 "meta":"Done-for-you pest control websites for termites, rodents, bed bugs and quarterly plans. $349 setup, $99/month, live in 48 hours with hosting and SEO.",
 "h1":"Pest control websites that <em>book the first treatment</em> and keep the plan",
 "lede":"Someone who just saw a mouse wants help today. We build pest control websites that answer fast, explain the treatment and sign them up for ongoing protection.",
 "searches":["pest control near me","termite inspection","rodent removal","bed bug treatment cost","quarterly pest control service"],
 "pains":[
  ("Urgency with a side of embarrassment","People want quick, discreet help. Your site has to feel calm, clear and fast to contact."),
  ("Every pest is its own search","Termites, rodents, bed bugs, ants and mosquitoes are searched separately. Each needs its own section."),
  ("Quarterly plans drive profit","Your site should present a protection plan as the obvious next step."),
  ("Pet and kid safety questions","Answering safety concerns on the page removes the biggest objection."),
 ],
 "features":[
  ("Pest by pest sections","Termites, rodents, bed bugs, ants, roaches and mosquitoes each named for search."),
  ("Protection plan offer","Quarterly or monthly plans laid out clearly."),
  ("Family and pet safety section","Answers the question every parent asks."),
  ("Free inspection form","Collects pest type and property details."),
  ("Commercial accounts section","Restaurants, offices and property managers, if you serve them."),
  ("Service area list","Every city and county you cover."),
 ],
 "pages":["Home with free inspection offer","Services: pest by pest plus protection plans","About and safety promise","Reviews","Contact with inspection form"],
 "example":("Example booking alert","Rodent inspection, garage","Wed 11:30 AM"),
 "faqs":[
  ("What should a pest control website include?","Clear sections for each pest you treat, a protection plan offer, safety info for pets and kids, reviews, license details and an easy inspection form. Every SitesThatBook pest site includes those."),
  ("Can you help me rank for termite and rodent searches?","Yes. Each pest gets a named section with its own heading, and your monthly blog posts can target seasonal pest searches."),
  ("Can I show my state license number?","Yes. We place it in the header area or footer where customers expect it."),
  ("How long does it take to launch?","48 hours after you submit the onboarding form."),
 ],
},
{
 "slug":"painting-contractor-websites","name":"Painting","who":"painting contractors","icon":"painting",
 "kw":"painting contractor websites",
 "title":"Painting Contractor Websites That Book Estimates | SitesThatBook",
 "meta":"Done-for-you websites for house painters and painting contractors with galleries and estimate forms. $349 setup, $99/month, live in 48 hours.",
 "h1":"Painting contractor websites that <em>book estimates</em>, not just compliments",
 "lede":"Homeowners hire painters on looks, reviews and how clearly the job is explained. We build painting websites that show off your finish work and make the estimate easy to request.",
 "searches":["house painters near me","interior painting cost","exterior house painting","cabinet painting service","commercial painting contractor"],
 "pains":[
  ("Your finish work is your best salesman","Without a strong gallery, you look like every other painter in town."),
  ("Interior and exterior buyers think differently","Each needs its own section with the right questions answered."),
  ("Prep and process sell the price","Explaining your prep work justifies your rate and wins the right customers."),
  ("Estimate requests with no detail","A form that asks for rooms or square footage saves you wasted trips."),
 ],
 "features":[
  ("Project gallery","Rooms, exteriors and cabinets shown in big, sharp photos."),
  ("Interior, exterior and cabinet sections","Each named for the searches homeowners use."),
  ("Our process section","Prep, protect, paint, clean up and walkthrough."),
  ("Paint brands and warranty","The brands you use and your workmanship warranty."),
  ("Estimate request form","Collects project type, rooms and timeline."),
  ("Service area list","Every town you paint in."),
 ],
 "pages":["Home with featured projects","Services: interior, exterior, cabinets, commercial","About and process","Reviews and gallery","Contact with estimate form"],
 "example":("Example booking alert","Exterior repaint estimate","Tue 5:00 PM"),
 "faqs":[
  ("Do you build websites for house painters?","Yes. Residential and commercial painting contractors get a gallery, process section and estimate form built in."),
  ("Can I update my gallery after launch?","Yes. Send new project photos as one of your 2 monthly updates and we add them."),
  ("Will the site mention the paint brands I use?","Yes, if you want. Tell us in the onboarding form."),
  ("Is there a money-back guarantee?","Yes. If you do not love the site on the launch call and we cannot fix it right then, we refund your $349 setup fee."),
 ],
},
{
 "slug":"pressure-washing-websites","name":"Pressure Washing","who":"pressure washing companies","icon":"washing",
 "kw":"pressure washing websites",
 "title":"Pressure Washing Websites That Get Booked | SitesThatBook",
 "meta":"Done-for-you pressure washing and soft washing websites with before and after galleries and quote forms. $349 setup, $99/month, live in 48 hours.",
 "h1":"Pressure washing websites that <em>show the difference</em> and get you booked",
 "lede":"Nothing sells pressure washing like a dirty to clean photo. We build pressure washing websites that lead with your results and make quote requests easy from any phone.",
 "searches":["pressure washing near me","house soft washing","driveway cleaning","roof cleaning service","deck and fence cleaning"],
 "pains":[
  ("Results are visual","If your before and after photos are not front and center, you are hiding your best sales tool."),
  ("Soft wash vs pressure wash confusion","Homeowners worry about damage. Explaining your method builds trust."),
  ("Lots of small jobs","Bundles like house plus driveway raise ticket size when they are shown on the site."),
  ("Seasonal spikes","Spring demand needs a site that is ready and ranking before the rush."),
 ],
 "features":[
  ("Before and after gallery","Side by side results that sell themselves."),
  ("Service sections by surface","House, roof, driveway, deck, fence and commercial each named for search."),
  ("Soft wash explainer","Explains your method and why it is safe for siding and roofs."),
  ("Bundle offers","House plus driveway packages shown clearly."),
  ("Quick quote form","Address, surfaces and photos if they have them."),
  ("Service area list","Every town you cover."),
 ],
 "pages":["Home with before and after showcase","Services: house, roof, concrete, decks, commercial","About and soft wash method","Reviews and gallery","Contact with quick quote form"],
 "example":("Example booking alert","House wash and driveway","Sat 8:30 AM"),
 "faqs":[
  ("What makes a good pressure washing website?","Big before and after photos, one section per surface you clean, a clear explanation of soft washing, reviews and a quick quote form. Your site gets all of it."),
  ("Can I add new before and after photos regularly?","Yes. Use your 2 monthly updates to add fresh results."),
  ("Do you build websites for soft washing companies?","Yes. Soft washing and exterior cleaning companies get the same setup with a method section that answers safety questions."),
  ("How do I get started?","Fill the onboarding form. We build your site and reveal it on a launch call 48 hours later."),
 ],
},
]

ICONS = {
 "hvac":'<path d="M12 2v20M4.9 4.9l14.2 14.2M2 12h20M4.9 19.1L19.1 4.9" stroke="currentColor" stroke-width="2" stroke-linecap="round"/>',
 "plumbing":'<path d="M5 3v6a3 3 0 003 3h8a3 3 0 013 3v6M5 7h4M15 21h8" stroke="currentColor" stroke-width="2" stroke-linecap="round" fill="none"/>',
 "roofing":'<path d="M2 12L12 4l10 8M5 10v10h14V10" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "electrical":'<path d="M13 2L4 14h7l-1 8 9-12h-7l1-8z" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "garage":'<path d="M3 21V9l9-6 9 6v12M7 21v-8h10v8M7 16h10" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "landscaping":'<path d="M12 22v-8M12 14c-4 0-7-3-7-7 4 0 7 3 7 7zm0 0c4 0 7-3 7-7-4 0-7 3-7 7z" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "cleaning":'<path d="M9 3h6v4l3 3v11H6V10l3-3V3zM9 14h6" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "pest":'<path d="M12 7a3 3 0 100-.01M8 11h8v4a4 4 0 01-8 0v-4zM4 9l4 2M20 9l-4 2M4 17l4-1M20 17l-4-1" stroke="currentColor" stroke-width="2" stroke-linecap="round" fill="none"/>',
 "painting":'<path d="M4 4h13v5H4zM17 6h3v6h-8v3M12 15v6" stroke="currentColor" stroke-width="2" stroke-linejoin="round" fill="none"/>',
 "washing":'<path d="M3 14h7l3-3h4M17 8v6M20 9l2-1M20 12h2M20 15l2 1M5 14v6" stroke="currentColor" stroke-width="2" stroke-linecap="round" fill="none"/>',
}
